HW6
GenesisEducationKyiv/hw1-se-school_2022-code-review-dandimog pull request #7
Opened 2022-10-03 13:26 UTC by dandimog

The decision towards the monolithic architecture was made in order not to overcomplicate the existing simple project structure. BitcoinCachingProxy is refactored.

2022-10-05 17:50 UTC, swefd requested changes

2022-10-05 17:50 UTC, swefd commented on src/services/decorators/BitcoinLoggingDecorator.ts
> +        }
Якщо виникне помилка при записі в файл, то користувачу прилетить `BAD_REQUEST` ?

Якщо так, то це не зовсім очікувана поведіка)

2022-10-05 17:50 UTC, swefd commented on src/services/decorators/BitcoinLoggingDecorator.ts
> +                `Response from ${this.bitcoinClient.NAME}: ${JSON.stringify(response)} \n`
Можливо роботу з файлом раціональніше кудись перемістити з декоратора?

2022-10-11 10:15 UTC, Larisa-Antsifrova commented
Hi, Daniil! I have checked the project's overall structure. As I understand you have chosen to separate the project files by layer :) Thank you for your work!

2022-10-11 11:27 UTC, swefd approved these changes

2022-10-13 21:38 UTC, merged